# Generated by Django 5.2.17 on 2026-09-11 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texts', '0002_review_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthologyCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=255, verbose_name='tytuł opowiadania')),
                ('fragment', models.TextField(verbose_name='fragment')),
                ('problem', models.TextField(verbose_name='co jest źle')),
                ('suggestion', models.TextField(verbose_name='propozycja poprawki')),
                ('status', models.CharField(choices=[('new', 'Nowa'), ('checking', 'W sprawdzaniu'), ('accepted', 'Przyjęta'), ('rejected', 'Odrzucona'), ('applied', 'Wprowadzona')], default='new', max_length=20, verbose_name='status zmiany')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='zgłoszono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
                ('anthology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='texts.anthology', verbose_name='antologia')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='zgłaszający')),
            ],
            options={
                'verbose_name': 'uwaga do antologii',
                'verbose_name_plural': 'uwagi do antologii',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('actor_name', models.CharField(blank=True, max_length=320, verbose_name='imię i nazwisko')),
                ('object_type', models.CharField(max_length=100, verbose_name='typ')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='identyfikator')),
                ('object_label', models.CharField(max_length=500, verbose_name='obiekt')),
                ('text_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('review_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('changes', models.JSONField(default=dict, verbose_name='zmiany')),
                ('superuser_only', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='osoba')),
            ],
            options={
                'verbose_name': 'wpis dziennika zmian',
                'verbose_name_plural': 'dziennik zmian',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
