# Generated by Django 5.2.17 on 2026-09-11 17:29

import django.db.models.deletion
from django.db import migrations, models


def link_existing_texts(apps, schema_editor):
    Correction = apps.get_model('core', 'AnthologyCorrection')
    Text = apps.get_model('texts', 'Text')
    database = schema_editor.connection.alias
    matches = {}
    for pk, anthology_id, title in Text.objects.using(database).values_list('pk', 'anthology_id', 'title').iterator():
        key = (anthology_id, ' '.join(title.split()).casefold())
        matches.setdefault(key, []).append(pk)
    for row in Correction.objects.using(database).filter(text__isnull=True).iterator():
        candidates = matches.get((row.anthology_id, ' '.join(row.story_title.split()).casefold()), [])
        if len(candidates) == 1:
            Correction.objects.using(database).filter(pk=row.pk).update(text_id=candidates[0])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('texts', '0002_review_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthologycorrection',
            name='submission_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='anthologycorrection',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anthology_corrections', to='texts.text', verbose_name='opowiadanie'),
        ),
        migrations.RunPython(link_existing_texts, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ChangeEvent',
        ),
    ]
