# Generated by Django 5.2.17 on 2026-09-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anthologycorrection_submission_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='adres e-mail')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='numer telefonu')),
                ('role', models.CharField(max_length=120, verbose_name='rola / obszar współpracy')),
                ('status', models.CharField(choices=[('new', 'Nowe zgłoszenie'), ('contacted', 'Kontakt nawiązany'), ('trial', 'Zadanie próbne'), ('accepted', 'Przyjęty'), ('rejected', 'Odrzucony'), ('withdrawn', 'Rezygnacja')], default='new', max_length=20, verbose_name='status')),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False, verbose_name='czarna lista')),
                ('blacklist_reason', models.TextField(blank=True, verbose_name='powód wpisania na czarną listę')),
                ('notes', models.TextField(blank=True, verbose_name='doświadczenie, dostępność i notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data zgłoszenia')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'zgłoszenie rekrutacyjne',
                'verbose_name_plural': 'rekrutacja',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
