# Generated by Django 5.2.17 on 2026-09-11 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_case_insensitive_comparisons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitment',
            options={'ordering': ('-submitted_at', '-pk'), 'verbose_name': 'zgłoszenie rekrutacyjne', 'verbose_name_plural': 'rekrutacja'},
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='blacklist_reason',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='is_blacklisted',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='role',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='department',
            field=models.CharField(choices=[('editors', 'Redaktorzy'), ('proofreaders', 'Korektorzy'), ('verifiers', 'Weryfikatorzy'), ('reviewers', 'Recenzenci'), ('post_layout', 'Korektorzy poskładowi'), ('audio_proofreaders', 'Korektorzy audiobooków'), ('narrators', 'Lektorzy'), ('sound', 'Dźwiękowcy'), ('illustrators', 'Ilustratorzy'), ('typesetters', 'Składacze'), ('designers', 'Graficy'), ('other', 'Inne')], default='other', max_length=30, verbose_name='dział'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='imię'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name='nazwisko'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='czy powiadomiono'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='notified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='data powiadomienia'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='submitted_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='data nadesłania'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='unofficial_notes',
            field=models.TextField(blank=True, verbose_name='uwagi nieoficjalne'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='uwagi'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='status',
            field=models.CharField(choices=[('new', 'Czeka na ocenę'), ('accepted', 'Przyjęte'), ('rejected', 'Odrzucone')], default='new', max_length=20, verbose_name='status'),
        ),
    ]
