# Generated by Django 5.2.17 on 2026-09-14 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recruitment_department_recruitment_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=254, verbose_name='konto')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='czas')),
                ('method', models.CharField(max_length=10, verbose_name='metoda')),
                ('action', models.CharField(max_length=255, verbose_name='działanie')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='obiekt')),
                ('path', models.CharField(max_length=1000, verbose_name='ścieżka')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='wynik HTTP')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_activities', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'aktywność użytkownika',
                'verbose_name_plural': 'aktywności użytkowników',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
