# Generated by Django 5.2.17 on 2026-09-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('channel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Wysyłanie / brak potwierdzenia'), ('sent', 'Wysłano'), ('failed', 'Odrzucono'), ('unknown', 'Brak potwierdzenia')], default='pending', max_length=12)),
                ('message_id', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wysyłka testowa Discord',
                'verbose_name_plural': 'wysyłki testowe Discord',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
