# Generated by Django 5.2.17 on 2026-09-14 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_discorddispatch'),
        ('texts', '0009_text_file_url_alter_anthology_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField(blank=True)),
                ('actor_name', models.CharField(max_length=300)),
                ('previous_status', models.CharField(max_length=100)),
                ('next_status', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('channel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('sending', 'Wysyłanie / brak potwierdzenia'), ('sent', 'Wysłano'), ('failed', 'Błąd wysyłki'), ('unknown', 'Brak potwierdzenia'), ('disabled', 'Brak skonfigurowanego kanału')], default='pending', max_length=12)),
                ('message_id', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='texts.text')),
            ],
            options={
                'verbose_name': 'zmiana workflow',
                'verbose_name_plural': 'zmiany workflow i powiadomienia Discord',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
