# Generated by Django 5.2.17 on 2026-09-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_workflowevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowevent',
            name='sending_started_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
