# Generated by Django 5.2.17 on 2026-09-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workflowevent_sending_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField()),
                ('version', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('model_label', 'object_id'), name='unique_edit_revision')],
            },
        ),
    ]
