# Generated by Django 5.2.17 on 2026-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_activity_spool_personal_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nazwa skrzynki')),
                ('host', models.CharField(help_text='Nazwa serwera, np. imap.example.com, bez https://.', max_length=253, verbose_name='serwer IMAP')),
                ('port', models.PositiveIntegerField(default=993, verbose_name='port')),
                ('security', models.CharField(choices=[('ssl', 'SSL/TLS (zwykle port 993)'), ('starttls', 'STARTTLS (zwykle port 143)')], default='ssl', max_length=8, verbose_name='szyfrowanie połączenia')),
                ('username', models.CharField(max_length=254, verbose_name='login')),
                ('encrypted_password', models.TextField(editable=False)),
                ('folder', models.CharField(default='INBOX', help_text='Nazwa folderu IMAP. Standardowa skrzynka odbiorcza: INBOX.', max_length=255, verbose_name='folder')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywna')),
            ],
            options={
                'verbose_name': 'skrzynka zgłoszeń',
                'verbose_name_plural': 'skrzynki zgłoszeń',
                'ordering': ('name', 'pk'),
            },
        ),
    ]
