# Generated by Django 5.2.17 on 2026-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mailboxconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_key', models.CharField(max_length=64)),
                ('uid_validity', models.PositiveBigIntegerField()),
                ('uid', models.PositiveBigIntegerField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mailbox_key', 'uid_validity', 'uid'), name='unique_mailbox_download')],
            },
        ),
    ]
