# Generated by Django 5.2.17 on 2026-09-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_mailboxconnection_recruitment_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adres e-mail')),
                ('premieres', models.BooleanField(default=False, verbose_name='newsletter o premierach')),
                ('recruitment', models.BooleanField(default=False, verbose_name='newsletter o naborach')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ostatnia aktualizacja')),
            ],
            options={
                'verbose_name': 'zgoda newsletterowa',
                'verbose_name_plural': 'zgody newsletterowe',
                'ordering': ('email', 'pk'),
            },
        ),
    ]
