# Generated by Django 5.2.17 on 2026-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_newsletterconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxdownload',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mailboxdownload',
            name='message_id',
            field=models.CharField(blank=True, max_length=998),
        ),
    ]
