# Generated by Django 5.2.17 on 2026-10-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mailboxconnection_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='mail_body',
            field=models.TextField(blank=True, verbose_name='treść wiadomości'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='mail_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='mail_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data wiadomości'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='mail_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='role z tematu'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='mail_sender',
            field=models.CharField(blank=True, max_length=2000, verbose_name='nadawca wiadomości'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='mail_subject',
            field=models.CharField(blank=True, max_length=2000, verbose_name='temat wiadomości'),
        ),
        migrations.CreateModel(
            name='RecruitmentMailSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_key', models.CharField(max_length=64)),
                ('uid_validity', models.PositiveBigIntegerField()),
                ('uid', models.PositiveBigIntegerField()),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_sources', to='core.recruitment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mailbox_key', 'uid_validity', 'uid'), name='unique_recruitment_mail_source')],
            },
        ),
    ]
