# Generated by Django 5.2.17 on 2026-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_recruitment_sample_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='imię i nazwisko z formularza'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='decision_reason',
            field=models.TextField(blank=True, verbose_name='uzasadnienie decyzji'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='mail_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='wybrane role'),
        ),
    ]
