# Generated by Django 5.2.17 on 2026-10-08 12:44

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_decisions(apps, schema_editor):
    Recruitment = apps.get_model('core', 'Recruitment')
    Decision = apps.get_model('core', 'RecruitmentRoleDecision')
    using = schema_editor.connection.alias
    # Frozen identifiers: no runtime imports in migrations.
    known = ('editors', 'proofreaders', 'verifiers', 'reviewers', 'narrators',
             'audio_proofreaders', 'illustrators', 'typesetters', 'post_layout',
             'promotion', 'other', 'sound', 'designers')
    batch = []
    for record in Recruitment.objects.using(using).all().iterator(chunk_size=500):
        roles = {role for role in (record.mail_roles or []) if isinstance(role, str) and role in known}
        roles = roles or {record.department if record.department in known else 'other'}
        for role in known:
            if role in roles:
                batch.append(Decision(recruitment_id=record.pk, role=role,
                    status=record.status if record.status in ('new', 'accepted', 'rejected') else 'new',
                    decision_reason=record.decision_reason, unofficial_notes=record.unofficial_notes))
        if len(batch) >= 500:
            Decision.objects.using(using).bulk_create(batch)
            batch = []
    if batch:
        Decision.objects.using(using).bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_recruitment_decision_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='status',
            field=models.CharField(choices=[('new', 'Czeka na ocenę'), ('accepted', 'Przyjęte'), ('rejected', 'Odrzucone'), ('mixed', 'Różne decyzje')], default='new', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='RecruitmentRoleDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, verbose_name='rola')),
                ('status', models.CharField(choices=[('new', 'Bez decyzji'), ('accepted', 'Przyjęty'), ('rejected', 'Odrzucony')], default='new', max_length=20, verbose_name='decyzja')),
                ('decision_reason', models.TextField(blank=True, verbose_name='uzasadnienie decyzji')),
                ('unofficial_notes', models.TextField(blank=True, verbose_name='nieoficjalne notatki')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_decisions', to='core.recruitment', verbose_name='zgłoszenie')),
            ],
            options={
                'verbose_name': 'decyzja dla roli',
                'verbose_name_plural': 'decyzje dla ról',
                'ordering': ('pk',),
                'constraints': [models.UniqueConstraint(fields=('recruitment', 'role'), name='unique_recruitment_role')],
            },
        ),
        migrations.RunPython(copy_existing_decisions, migrations.RunPython.noop),
    ]
