# Generated by Django 5.2.17 on 2026-10-10 01:10

import core.audiobook_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_recruitment_role_decisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAudiobookSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('mega_url', models.URLField(default='https://mega.nz/', help_text='Publiczny link wspólny dla opowiadań na stronie zewnętrznej.', max_length=1000, validators=[core.audiobook_validators.validate_mega_url], verbose_name='wspólny link MegaNZ')),
                ('guidelines', models.TextField(blank=True, default='', help_text='Tekst publiczny. Można go rozwinąć na stronie i pobrać jako TXT.', max_length=40000, verbose_name='wytyczne')),
            ],
            options={
                'verbose_name': 'ustawienia zewnętrznych audiobooków',
                'verbose_name_plural': 'Zewnętrzne audiobooki – ustawienia',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_public_audiobook_settings')],
            },
        ),
    ]
