# Generated by Django 5.2.18 on 2026-10-10 01:25

import core.audiobook_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_public_audiobook_settings'),
        ('texts', '0031_cover_typography_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Do nagrania'), ('recording', 'Trwa nagrywanie'), ('proofreading', 'Korekta'), ('corrections', 'Nanoszenie poprawek'), ('editing', 'Montaż'), ('awaiting_publication', 'Czeka na publikację'), ('published', 'Opublikowane')], db_index=True, default='pending', max_length=24, verbose_name='status audiobooka')),
                ('narrator_name', models.CharField(blank=True, max_length=255, verbose_name='lektor – imię i nazwisko')),
                ('narrator_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail lektora')),
                ('engineer_name', models.CharField(blank=True, max_length=255, verbose_name='dźwiękowiec – imię i nazwisko')),
                ('engineer_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail dźwiękowca')),
                ('recording_started_at', models.DateField(blank=True, null=True, verbose_name='rozpoczęcie nagrywania')),
                ('proofreading_started_at', models.DateField(blank=True, null=True, verbose_name='rozpoczęcie korekty')),
                ('corrections_started_at', models.DateField(blank=True, null=True, verbose_name='rozpoczęcie nanoszenia poprawek')),
                ('editing_started_at', models.DateField(blank=True, null=True, verbose_name='rozpoczęcie montażu')),
                ('awaiting_publication_started_at', models.DateField(blank=True, null=True, verbose_name='oczekiwanie na publikację od')),
                ('premiere_date', models.DateField(blank=True, null=True, verbose_name='data premiery')),
                ('youtube_url', models.URLField(blank=True, max_length=1000, validators=[core.audiobook_validators.validate_youtube_url], verbose_name='YouTube')),
                ('hearthis_url', models.URLField(blank=True, max_length=1000, validators=[core.audiobook_validators.validate_hearthis_url], verbose_name='HearThis')),
                ('proofreader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proofread_audiobooks', to=settings.AUTH_USER_MODEL, verbose_name='korektor audiobooka')),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audiobook', to='texts.text', verbose_name='tekst')),
            ],
            options={
                'verbose_name': 'audiobook',
                'verbose_name_plural': 'Audiobooki – przypisania i publikacje',
                'ordering': ('text__anthology__title', 'text__title', 'pk'),
            },
        ),
    ]
