# Generated by Django 5.2.18 on 2026-10-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_audiobook_production'),
        ('texts', '0031_cover_typography_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiobookStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('pending', 'Do nagrania'), ('recording', 'Trwa nagrywanie'), ('proofreading', 'Korekta'), ('corrections', 'Nanoszenie poprawek'), ('editing', 'Montaż'), ('awaiting_publication', 'Czeka na publikację'), ('published', 'Opublikowane')], max_length=24, verbose_name='etap')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='data rozpoczęcia')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='data zakończenia')),
                ('is_completed', models.BooleanField(default=False, verbose_name='zakończony')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiobook_stages', to='texts.text', verbose_name='tekst')),
            ],
            options={
                'verbose_name': 'etap audiobooka',
                'verbose_name_plural': 'Historia etapów audiobooków',
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='audiobook',
            name='active_stage',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for', to='core.audiobookstage', verbose_name='trwający etap'),
        ),
        migrations.AddConstraint(
            model_name='audiobookstage',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='audio_stage_end_after_start'),
        ),
    ]
