# Generated by Django 5.2.18 on 2026-10-10 02:03

import core.audiobook_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_audiobook_stage_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='additional_links',
            field=models.JSONField(blank=True, default=list, help_text='Lista obiektów: service (youtube/hearthis), part (numer części), url.', validators=[core.audiobook_validators.validate_audio_links], verbose_name='linki do kolejnych części'),
        ),
        migrations.AddField(
            model_name='audiobookstage',
            name='import_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='audiobookstage',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audiobook_stage_history', to=settings.AUTH_USER_MODEL, verbose_name='wykonawca korekty'),
        ),
    ]
