# Generated by Django 5.2.18 on 2026-10-10 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_audiobook_import_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentroledecision',
            name='reason_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_reasons', to=settings.AUTH_USER_MODEL, verbose_name='autor uzasadnienia'),
        ),
        migrations.AddField(
            model_name='recruitmentroledecision',
            name='reason_author_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='podpis autora uzasadnienia'),
        ),
        migrations.AddField(
            model_name='recruitmentroledecision',
            name='reason_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data zmiany uzasadnienia'),
        ),
        migrations.CreateModel(
            name='AudioContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='imię i nazwisko')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='adres e-mail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_contacts', to=settings.AUTH_USER_MODEL, verbose_name='powiązane konto (opcjonalne)')),
            ],
            options={
                'verbose_name': 'lektor / dźwiękowiec',
                'verbose_name_plural': 'Lektorzy i dźwiękowcy',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='audiobook',
            name='engineer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engineered_books', to='core.audiocontributor', verbose_name='profil dźwiękowca'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='narrator_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='narrated_books', to='core.audiocontributor', verbose_name='profil lektora'),
        ),
        migrations.AddConstraint(
            model_name='audiocontributor',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='unique_audio_contact_pair'),
        ),
    ]
