# Generated by Django 5.2.18 on 2026-10-10 10:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_populate_audio_contacts'),
        ('texts', '0031_cover_typography_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLayoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_from', models.PositiveIntegerField(verbose_name='strona od')),
                ('page_to', models.PositiveIntegerField(verbose_name='strona do')),
                ('status', models.CharField(choices=[('assigned', 'Przydzielony'), ('in_progress', 'W trakcie'), ('completed', 'Zakończony')], db_index=True, default='assigned', max_length=16, verbose_name='status')),
                ('assigned_start', models.DateField(default=django.utils.timezone.localdate, verbose_name='przydzielony – rozpoczęcie')),
                ('assigned_end', models.DateField(blank=True, null=True, verbose_name='przydzielony – zakończenie')),
                ('work_start', models.DateField(blank=True, null=True, verbose_name='w trakcie – rozpoczęcie')),
                ('work_end', models.DateField(blank=True, null=True, verbose_name='w trakcie – zakończenie')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='zakończony – data zakończenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data przypisania')),
                ('creation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('anthology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_layout_assignments', to='texts.anthology', verbose_name='antologia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_post_layout_assignments', to=settings.AUTH_USER_MODEL, verbose_name='przypisał')),
                ('proofreader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_layout_assignments', to=settings.AUTH_USER_MODEL, verbose_name='korektor poskładowy')),
            ],
            options={
                'verbose_name': 'przydział korekty poskładowej',
                'verbose_name_plural': 'Korekta poskładowa – przydziały',
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('page_from__gte', 1), ('page_to__gte', models.F('page_from'))), name='post_layout_page_range'), models.CheckConstraint(condition=models.Q(models.Q(('assigned_end__isnull', True), ('completed_on__isnull', True), ('status', 'assigned'), ('work_end__isnull', True), ('work_start__isnull', True)), models.Q(('assigned_end', models.F('work_start')), ('assigned_end__isnull', False), ('completed_on__isnull', True), ('status', 'in_progress'), ('work_end__isnull', True), ('work_start__gte', models.F('assigned_start')), ('work_start__isnull', False)), models.Q(('assigned_end', models.F('work_start')), ('assigned_end__isnull', False), ('completed_on__gte', models.F('work_start')), ('completed_on__isnull', False), ('status', 'completed'), ('work_end', models.F('completed_on')), ('work_end__isnull', False), ('work_start__gte', models.F('assigned_start')), ('work_start__isnull', False)), _connector='OR'), name='post_layout_status_dates')],
            },
        ),
    ]
