# Generated by Django 5.2.18 on 2026-10-10 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_audio_montage_labels'),
        ('texts', '0032_abandoned_anthology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postlayoutassignment',
            name='post_layout_page_range',
        ),
        migrations.RemoveConstraint(
            model_name='postlayoutassignment',
            name='post_layout_status_dates',
        ),
        migrations.AddField(
            model_name='postlayoutassignment',
            name='historical',
            field=models.BooleanField(default=False, editable=False, verbose_name='historyczna korekta ze stopki'),
        ),
        migrations.AlterField(
            model_name='postlayoutassignment',
            name='assigned_start',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='przydzielony – rozpoczęcie'),
        ),
        migrations.AlterField(
            model_name='postlayoutassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_post_layout_assignments', to=settings.AUTH_USER_MODEL, verbose_name='przypisał'),
        ),
        migrations.AlterField(
            model_name='postlayoutassignment',
            name='page_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='strona od'),
        ),
        migrations.AlterField(
            model_name='postlayoutassignment',
            name='page_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='strona do'),
        ),
        migrations.AddConstraint(
            model_name='postlayoutassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('page_from__gte', 1), ('page_from__isnull', False), ('page_to__gte', models.F('page_from')), ('page_to__isnull', False)), models.Q(('historical', True), ('page_from__isnull', True), ('page_to__isnull', True)), _connector='OR'), name='post_layout_page_range'),
        ),
        migrations.AddConstraint(
            model_name='postlayoutassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_end__isnull', True), ('assigned_start__isnull', True), ('completed_on__isnull', True), ('historical', True), ('status', 'completed'), ('work_end__isnull', True), ('work_start__isnull', True)), models.Q(('assigned_start__isnull', False), models.Q(models.Q(('assigned_end__isnull', True), ('completed_on__isnull', True), ('status', 'assigned'), ('work_end__isnull', True), ('work_start__isnull', True)), models.Q(('assigned_end', models.F('work_start')), ('assigned_end__isnull', False), ('completed_on__isnull', True), ('status', 'in_progress'), ('work_end__isnull', True), ('work_start__gte', models.F('assigned_start')), ('work_start__isnull', False)), models.Q(('assigned_end', models.F('work_start')), ('assigned_end__isnull', False), ('completed_on__gte', models.F('work_start')), ('completed_on__isnull', False), ('status', 'completed'), ('work_end', models.F('completed_on')), ('work_end__isnull', False), ('work_start__gte', models.F('assigned_start')), ('work_start__isnull', False)), _connector='OR')), _connector='OR'), name='post_layout_status_dates'),
        ),
        migrations.AddConstraint(
            model_name='postlayoutassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('historical', True), ('status', 'completed')), models.Q(('created_by__isnull', False), ('historical', False)), _connector='OR'), name='post_layout_history_state'),
        ),
    ]
