# Generated by Django 5.2.18 on 2026-10-10 13:00

import django.db.models.deletion
from django.db import migrations, models


def seed_descriptions(apps, schema_editor):
    Book = apps.get_model('texts', 'Anthology')
    Description = apps.get_model('core', 'AudioDescription')
    alias = schema_editor.connection.alias
    Description.objects.using(alias).bulk_create([
        Description(anthology_id=pk) for pk in Book.objects.using(alias).filter(is_novel=False).values_list('pk', flat=True)
    ], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_post_layout_historical_credits'),
        ('people', '0015_retire_generic_coordinator'),
        ('texts', '0034_audio_descriptions_and_banery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_description', to='texts.anthology', verbose_name='antologia')),
                ('controllers', models.ManyToManyField(blank=True, related_name='controlled_audio_descriptions', to='people.person', verbose_name='osoby do kontroli')),
            ],
            options={
                'verbose_name': 'audiodeskrypcja',
                'verbose_name_plural': 'audiodeskrypcje',
                'ordering': ('anthology__title', 'pk'),
            },
        ),
        migrations.RunPython(seed_descriptions, migrations.RunPython.noop),
    ]
