# Generated by Django 5.2.18 on 2026-10-10 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def initialize_completed(apps, schema_editor):
    Task = apps.get_model('texts', 'AnthologyTask')
    Description = apps.get_model('core', 'AudioDescription')
    alias = schema_editor.connection.alias
    completed = Task.objects.using(alias).filter(task_type='audio_description', status='ready').values('anthology_id')
    Description.objects.using(alias).filter(anthology_id__in=completed).update(stage='completed')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_audio_descriptions_and_banery'),
        ('people', '0015_retire_generic_coordinator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodescription',
            name='content',
            field=models.TextField(blank=True, verbose_name='treść audiodeskrypcji'),
        ),
        migrations.AddField(
            model_name='audiodescription',
            name='stage',
            field=models.CharField(choices=[('writing', 'Pisanie AD'), ('consultation', 'Konsultacja'), ('proofreading', 'Korekta'), ('completed', 'Zakończone')], default='writing', max_length=20, verbose_name='etap prac'),
        ),
        migrations.AlterField(
            model_name='audiodescription',
            name='controllers',
            field=models.ManyToManyField(blank=True, related_name='controlled_audio_descriptions', to='people.person', verbose_name='konsultacja – osoby do kontroli'),
        ),
        migrations.CreateModel(
            name='AudioDescriptionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(editable=False, max_length=255, verbose_name='podpis autora')),
                ('content', models.TextField(verbose_name='uwaga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data wpisania')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor uwagi')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.audiodescription', verbose_name='audiodeskrypcja')),
            ],
            options={
                'verbose_name': 'uwaga do audiodeskrypcji',
                'verbose_name_plural': 'uwagi do audiodeskrypcji',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.RunPython(initialize_completed, migrations.RunPython.noop),
    ]
