# Generated by Django 5.2.18 on 2026-10-10 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_audio_description_content_and_notes'),
        ('texts', '0036_whole_extract_volumes_cover_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postlayoutassignment',
            name='post_layout_status_dates',
        ),
        migrations.AddConstraint(
            model_name='postlayoutassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('historical', True), ('status', 'completed'), models.Q(models.Q(('assigned_end__isnull', True), ('work_start__isnull', True)), models.Q(('assigned_end', models.F('work_start')), ('assigned_end__isnull', False), ('work_start__isnull', False)), _connector='OR'), models.Q(models.Q(('completed_on__isnull', True), ('work_end__isnull', True)), models.Q(('completed_on__isnull', False), ('work_end', models.F('completed_on')), ('work_end__isnull', False)), _connector='OR'), models.Q(('assigned_start__isnull', True), ('work_start__isnull', True), ('work_start__gte', models.F('assigned_start')), _connector='OR'), models.Q(('work_start__isnull', True), ('completed_on__isnull', True), ('completed_on__gte', models.F('work_start')), _connector='OR'), models.Q(('assigned_start__isnull', True), ('completed_on__isnull', True), ('completed_on__gte', models.F('assigned_start')), _connector='OR')), models.Q(('assigned_start__isnull', False), models.Q(models.Q(('assigned_end__isnull', True), ('completed_on__isnull', True), ('status', 'assigned'), ('work_end__isnull', True), ('work_start__isnull', True)), models.Q(('assigned_end', models.F('work_start')), ('assigned_end__isnull', False), ('completed_on__isnull', True), ('status', 'in_progress'), ('work_end__isnull', True), ('work_start__gte', models.F('assigned_start')), ('work_start__isnull', False)), models.Q(('assigned_end', models.F('work_start')), ('assigned_end__isnull', False), ('completed_on__gte', models.F('work_start')), ('completed_on__isnull', False), ('status', 'completed'), ('work_end', models.F('completed_on')), ('work_end__isnull', False), ('work_start__gte', models.F('assigned_start')), ('work_start__isnull', False)), _connector='OR')), _connector='OR'), name='post_layout_status_dates'),
        ),
    ]
