# Generated by Django 5.2.18 on 2026-10-10 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def close_final_stages(apps, schema_editor):
    """"Opublikowane" is the final state and "Do nagrania" is not a stage."""
    db = schema_editor.connection.alias
    Audiobook = apps.get_model('core', 'Audiobook')
    Stage = apps.get_model('core', 'AudiobookStage')
    for audio in Audiobook.objects.using(db).filter(active_stage__stage_type__in=('published', 'pending')).select_related('active_stage'):
        stage = audio.active_stage
        stage.is_completed = True
        stage.ended_at = stage.ended_at or stage.started_at
        stage.save(update_fields=['is_completed', 'ended_at'])
        audio.active_stage = None
        audio.save(update_fields=['active_stage'])
    Stage.objects.using(db).filter(stage_type='published', is_completed=False).update(is_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_historical_post_layout_partial_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="postlayoutassignment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="usunięto",
            ),
        ),
        migrations.AddField(
            model_name="postlayoutassignment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_post_layout_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usunął",
            ),
        ),
        migrations.AddField(
            model_name="workflowevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("workflow", "Workflow tekstu"),
                    ("audiobook", "Produkcja audiobooka"),
                ],
                db_index=True,
                default="workflow",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="audiodescription",
            name="stage",
            field=models.CharField(
                choices=[
                    ("writing", "Pisanie AD"),
                    ("consultation", "Konsultacja"),
                    ("proofreading", "Korekta audiodeskrypcji"),
                    ("completed", "Zakończone"),
                ],
                default="writing",
                max_length=20,
                verbose_name="etap prac",
            ),
        ),
        migrations.RunPython(close_final_stages, migrations.RunPython.noop),
    ]
