# Generated by Django 5.2.18 on 2026-10-10 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_post_layout_history_audiobook_events"),
        ("texts", "0038_anthologytask_not_applicable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="postlayoutassignment",
            name="post_layout_page_range",
        ),
        migrations.AddConstraint(
            model_name="postlayoutassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("page_from__gte", 1),
                        ("page_from__isnull", False),
                        ("page_to__gte", models.F("page_from")),
                        ("page_to__isnull", False),
                    ),
                    models.Q(("page_from__isnull", True), ("page_to__isnull", True)),
                    _connector="OR",
                ),
                name="post_layout_page_range",
            ),
        ),
    ]
