# Generated by Django 5.2.18 on 2026-10-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_post_layout_optional_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="anthologycorrection",
            name="reporter_name",
            field=models.CharField(
                blank=True,
                help_text="Imię i nazwisko z importu, gdy zgłaszający nie ma konta w CMS.",
                max_length=200,
                verbose_name="zgłaszający (z importu)",
            ),
        ),
        migrations.AlterField(
            model_name="anthologycorrection",
            name="fragment",
            field=models.TextField(blank=True, verbose_name="fragment"),
        ),
        migrations.AlterField(
            model_name="anthologycorrection",
            name="problem",
            field=models.TextField(blank=True, verbose_name="co jest źle"),
        ),
        migrations.AlterField(
            model_name="anthologycorrection",
            name="suggestion",
            field=models.TextField(blank=True, verbose_name="propozycja poprawki"),
        ),
    ]
