# Generated by Django 5.2.17 on 2026-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='numer telefonu'),
        ),
    ]
