# Generated by Django 5.2.17 on 2026-09-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='imię i nazwisko / opis')),
                ('email', models.EmailField(help_text='Dopasowanie zgłoszeń po e-mailu, bez rozróżniania wielkości liter. Nie tworzy profilu autora.', max_length=254, unique=True, verbose_name='adres e-mail')),
                ('notes', models.TextField(blank=True, verbose_name='notatka')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny wpis')),
            ],
            options={
                'verbose_name': 'niezależny wpis czarnej listy',
                'verbose_name_plural': 'czarna lista — wpisy niezależne',
                'ordering': ('name', 'email', 'pk'),
            },
        ),
        migrations.AlterField(
            model_name='authornote',
            name='content',
            field=models.TextField(blank=True, verbose_name='treść notatki'),
        ),
    ]
