# Generated by Django 5.2.17 on 2026-09-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_optional_note_independent_blacklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistentry',
            options={'ordering': ('name', 'email', 'pk'), 'verbose_name': 'niezależny wpis czarnej listy', 'verbose_name_plural': 'czarna lista – wpisy niezależne'},
        ),
    ]
