# Generated by Django 5.2.17 on 2026-09-11 21:07

import core.normalization
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_blacklistedauthor'),
        ('texts', '0002_review_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='adres e-mail')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='numer telefonu')),
                ('title', models.CharField(max_length=255, verbose_name='tytuł')),
                ('submitted_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='data nadesłania')),
                ('recruitment', models.CharField(max_length=255, verbose_name='nabór')),
                ('status', models.CharField(choices=[('new', 'Oczekuje'), ('accepted', 'Przyjęte'), ('rejected', 'Odrzucone')], default='new', max_length=20, verbose_name='decyzja')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracts', to='authors.author', verbose_name='autor')),
            ],
            options={
                'verbose_name': 'ekstrakt',
                'verbose_name_plural': 'ekstrakty',
                'ordering': ('-submitted_at', '-pk'),
            },
            bases=(core.normalization.NormalizedModelMixin, models.Model),
        ),
    ]
