# Generated by Django 5.2.17 on 2026-09-12 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_add_typesetter_role'),
        ('texts', '0004_grouped_extracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_historical',
            field=models.BooleanField(default=False, editable=False, verbose_name='tekst historyczny'),
        ),
        migrations.CreateModel(
            name='HistoricalTextAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255, verbose_name='nazwa osoby ze źródła')),
                ('role', models.CharField(choices=[('editor', 'Redaktor'), ('proofreader', 'Korektor'), ('verifier', 'Weryfikator'), ('editing_coordinator', 'Koordynator redakcji'), ('verification_coordinator', 'Koordynator weryfikacji'), ('editing_verifier', 'Weryfikacja redakcji'), ('final_reader', 'Sczytanie')], max_length=30, verbose_name='rola')),
                ('position', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='numer roli')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='rozpoczęcie')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='zakończenie')),
                ('is_completed', models.BooleanField(default=False, verbose_name='potwierdzone wykonanie')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_text_assignments', to='people.person', verbose_name='osoba')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_assignments', to='texts.text', verbose_name='tekst')),
            ],
            options={
                'verbose_name': 'historyczne przypisanie do tekstu',
                'verbose_name_plural': 'historyczne przypisania do tekstów',
                'ordering': ('text__title', 'role', 'position', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('text', 'role', 'position'), name='unique_historical_text_role_pos'), models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='historical_position_positive'), models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='historical_dates_order')],
            },
        ),
    ]
