# Generated by Django 5.2.17 on 2026-09-12 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_add_typesetter_role'),
        ('texts', '0005_text_is_historical_historicaltextassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltextassignment',
            options={'ordering': ('text__title', 'role', 'position', 'participant', 'pk'), 'verbose_name': 'historyczne przypisanie do tekstu', 'verbose_name_plural': 'historyczne przypisania do tekstów'},
        ),
        migrations.RemoveConstraint(
            model_name='historicaltextassignment',
            name='unique_historical_text_role_pos',
        ),
        migrations.AddField(
            model_name='historicaltextassignment',
            name='participant',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='numer uczestnika roli'),
        ),
        migrations.AddField(
            model_name='historicaltextassignment',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='LP w tabeli źródłowej'),
        ),
        migrations.AddField(
            model_name='historicaltextassignment',
            name='source_status',
            field=models.CharField(blank=True, choices=[('ready', 'Gotowe'), ('withdrawn', 'WYCOFANY')], max_length=12, verbose_name='status tekstu w źródle'),
        ),
        migrations.AddConstraint(
            model_name='historicaltextassignment',
            constraint=models.UniqueConstraint(fields=('text', 'role', 'position', 'participant'), name='unique_history_role_participant'),
        ),
        migrations.AddConstraint(
            model_name='historicaltextassignment',
            constraint=models.CheckConstraint(condition=models.Q(('participant__gte', 1)), name='historical_participant_positive'),
        ),
    ]
