# Generated by Django 5.2.17 on 2026-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_email'),
        ('texts', '0006_alter_historicaltextassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='historical_source',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='źródło importu historycznego'),
        ),
        migrations.AddField(
            model_name='text',
            name='historical_source_row',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='LP importu historycznego'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('historical_source', 'historical_source_row'), name='unique_text_historical_source'),
        ),
    ]
