# Generated by Django 6.0.8 on 2026-09-12 16:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_email'),
        ('people', '0006_add_coordinator_roles'),
        ('texts', '0007_text_historical_source_text_historical_source_row_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='coauthors',
            field=models.ManyToManyField(blank=True, help_text='Dodatkowi autorzy, poza autorem głównym.', related_name='coauthored_review_submissions', to='authors.author', verbose_name='współautorzy'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='historical_person',
            field=models.ForeignKey(blank=True, help_text='Profil osoby bez wymogu posiadania konta; tylko dla archiwum.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_review_assignments', to='people.person', verbose_name='recenzent historyczny'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='adres e-mail'),
        ),
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='gatunek'),
        ),
        migrations.AlterField(
            model_name='review',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='długość'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='assigned_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='data przydzielenia'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='opinion_changed_at',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, editable=False, null=True, verbose_name='data zmiany opinii'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('length__isnull', True), ('old_reviews', True)), models.Q(('length__gte', 1), ('length__isnull', False)), _connector='OR'), name='review_length_required_unless_old'),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(fields=('review', 'historical_person'), name='unique_historical_reviewer'),
        ),
    ]
