# Generated by Django 5.2.17 on 2026-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0008_historical_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='aktualny plik lub folder'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='status',
            field=models.CharField(choices=[('published', 'Wydane'), ('ready', 'Gotowe'), ('unpublished', 'Niewydane'), ('in_preparation', 'W przygotowaniu')], default='unpublished', max_length=20, verbose_name='status'),
        ),
    ]
