# Generated by Django 5.2.17 on 2026-09-15 13:34

from django.db import migrations, models


def map_statuses(apps, schema_editor):
    anthologies = apps.get_model('texts', 'Anthology').objects.using(schema_editor.connection.alias)
    anthologies.filter(status='published').update(status='ready')
    anthologies.filter(status='unpublished').update(status='in_preparation')


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0009_text_file_url_alter_anthology_status'),
    ]

    operations = [
        migrations.RunPython(map_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='anthology',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'W przygotowaniu'), ('ready', 'Gotowe')], default='in_preparation', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='text',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='folder Dropbox'),
        ),
    ]
