# Generated by Django 5.2.17 on 2026-09-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0010_alter_anthology_status_alter_text_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthology',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'W przygotowaniu'), ('ready', 'Gotowa')], default='in_preparation', max_length=20, verbose_name='status'),
        ),
    ]
