# Generated by Django 5.2.17 on 2026-09-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0012_remove_legacy_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='old_reviews',
            field=models.BooleanField(db_index=True, default=False, help_text='Oddane opinie archiwalne są liczone do dorobku, bez wpływu na bieżące obciążenie i przydzielanie pracy.', verbose_name='stare recenzje'),
        ),
    ]
