# Generated by Django 5.2.17 on 2026-09-27 16:59

from django.db import migrations, models


def align_open_statuses(apps, schema_editor):
    Review = apps.get_model('texts', 'Review')
    Assignment = apps.get_model('texts', 'ReviewAssignment')
    alias = schema_editor.connection.alias
    assigned = Assignment.objects.using(alias).values('review_id')
    reviews = Review.objects.using(alias).filter(old_reviews=False, status__in=('new','in_review'))
    reviews.filter(pk__in=assigned).update(status='in_review')
    reviews.exclude(pk__in=assigned).update(status='new')


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0013_alter_review_old_reviews'),
    ]

    operations = [
        migrations.RunPython(align_open_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('new', 'Do recenzji'), ('in_review', 'W recenzjach'), ('to_decide', 'Do decyzji'), ('accepted', 'Przyjęty'), ('rejected', 'Odrzucony'), ('withdrawn', 'Wycofany')], db_index=True, default='new', max_length=20, verbose_name='status'),
        ),
    ]
