# Generated by Django 5.2.17 on 2026-09-28 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0014_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_message',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='wiadomość od autora – tylko superuser'),
        ),
    ]
