# Generated by Django 5.2.17 on 2026-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0015_review_author_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='coordinator_note_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='data zapisania notatki koordynatora'),
        ),
    ]
