# Generated by Django 5.2.17 on 2026-09-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0016_text_coordinator_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_pseudonym',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='pseudonim autora'),
        ),
    ]
