# Generated by Django 5.2.17 on 2026-09-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0017_review_author_pseudonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='publication_detached',
            field=models.BooleanField(default=False, help_text='Nie pokazuj jako nowego tekstu do przeniesienia. Odznacz wyłącznie, jeśli świadomie chcesz ponownie utworzyć tekst.', verbose_name='Świadomie odłączono od tekstu'),
        ),
    ]
