# Generated by Django 5.2.17 on 2026-10-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0019_review_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='tags',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='tagi'),
        ),
    ]
