# Generated by Django 5.2.17 on 2026-10-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_blacklistentry_options'),
        ('texts', '0021_text_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthology',
            name='is_translated',
            field=models.BooleanField(db_index=True, default=False, help_text='Antologia i jej teksty są widoczne w sekcji Tłumaczenia oraz w panelu admina.', verbose_name='tłumaczone'),
        ),
        migrations.CreateModel(
            name='TextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='texts.text', verbose_name='tekst')),
                ('translators', models.ManyToManyField(blank=True, related_name='translations', to='authors.author', verbose_name='tłumacze')),
            ],
            options={
                'verbose_name': 'tłumaczenie',
                'verbose_name_plural': 'tłumaczenia',
                'ordering': ('text__anthology__title', 'text__title', 'pk'),
            },
        ),
    ]
