# Generated by Django 5.2.17 on 2026-10-05 16:08

from django.db import migrations, models


def add_audio_tasks(apps, schema_editor):
    Task = apps.get_model('texts', 'AnthologyTask')
    Book = apps.get_model('texts', 'Anthology')
    db = schema_editor.connection.alias
    for pk in Book.objects.using(db).values_list('pk', flat=True).iterator():
        Task.objects.using(db).get_or_create(anthology_id=pk, task_type='audio_description',
                                           defaults={'status':'not_commissioned'})


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0023_translation_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttranslation',
            name='original_verifier',
            field=models.CharField(blank=True, help_text='Imię i nazwisko osoby weryfikującej przekład z oryginałem.', max_length=255, verbose_name='Weryfikacja z oryginałem'),
        ),
        migrations.AlterField(
            model_name='anthologytask',
            name='task_type',
            field=models.CharField(choices=[('typesetting', 'Skład'), ('blurb', 'Blurb'), ('banners', 'Bannery'), ('audio_description', 'Audiodeskrypcja')], max_length=20, verbose_name='rodzaj zadania'),
        ),
        migrations.RunPython(add_audio_tasks, migrations.RunPython.noop),
    ]
