# Generated by Django 5.2.17 on 2026-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0024_texttranslation_original_verifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='for_recording',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Do nagrywania'),
        ),
    ]
