# Generated by Django 5.2.17 on 2026-10-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0025_text_for_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='audiobook_blacklisted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Czarna lista audiobooków'),
        ),
    ]
