# Generated by Django 5.2.17 on 2026-10-06 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_blacklistentry_options'),
        ('texts', '0026_text_audiobook_blacklisted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='gatunek')),
                ('tags', models.TextField(blank=True, max_length=5000, verbose_name='tagi')),
                ('content_warnings', models.TextField(blank=True, verbose_name='trigger warningi')),
                ('file_url', models.URLField(blank=True, max_length=1000, verbose_name='folder powieści')),
                ('notes', models.TextField(blank=True, verbose_name='ustalenia i notatki do całej powieści')),
                ('approved_signature', models.CharField(blank=True, editable=False, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'dane powieści',
                'verbose_name_plural': 'Dane powieści',
            },
        ),
        migrations.CreateModel(
            name='VocabularyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tag', 'Tag'), ('genre', 'Gatunek')], max_length=8, verbose_name='rodzaj')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa')),
                ('key', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'hasło słownika',
                'verbose_name_plural': 'Słownik tagów i gatunków',
                'ordering': ('kind', 'name', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='anthology',
            name='is_novel',
            field=models.BooleanField(db_index=True, default=False, verbose_name='powieść'),
        ),
        migrations.AddField(
            model_name='text',
            name='chapter_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='numer rozdziału'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('anthology', 'chapter_number'), name='unique_novel_chapter_number'),
        ),
        migrations.AddField(
            model_name='novelprofile',
            name='anthology',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='novel', to='texts.anthology', verbose_name='powieść'),
        ),
        migrations.AddField(
            model_name='novelprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novelprofile',
            name='authors',
            field=models.ManyToManyField(blank=True, to='authors.author', verbose_name='autorzy'),
        ),
        migrations.AddField(
            model_name='vocabularyterm',
            name='canonical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='texts.vocabularyterm', verbose_name='nazwa docelowa'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyterm',
            constraint=models.UniqueConstraint(fields=('kind', 'key'), name='unique_vocabulary_term'),
        ),
    ]
