# Generated by Django 5.2.17 on 2026-10-06 16:31

import django.core.validators
from django.db import migrations, models


def number_existing_chapters(apps, schema_editor):
    Text = apps.get_model('texts', 'Text')
    Novel = apps.get_model('texts', 'NovelProfile')
    alias = schema_editor.connection.alias
    changed_books = set()
    for chapter in Text.objects.using(alias).filter(anthology__is_novel=True).iterator():
        title = f'Rozdział {chapter.chapter_number}'
        if chapter.title != title:
            Text.objects.using(alias).filter(pk=chapter.pk).update(title=title)
            changed_books.add(chapter.anthology_id)
    Novel.objects.using(alias).filter(anthology_id__in=changed_books).update(approved_signature='')


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_blacklistentry_options'),
        ('texts', '0028_seed_vocabulary'),
    ]

    operations = [
        migrations.RunPython(number_existing_chapters, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='text',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='długość'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.CheckConstraint(condition=models.Q(('chapter_number__isnull', False), ('length__isnull', False), _connector='OR'), name='ordinary_text_requires_length'),
        ),
    ]
