# Generated by Django 5.2.17 on 2026-10-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0029_numbered_chapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelprofile',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='novelprofile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='novelprofile',
            name='approved_signature',
        ),
    ]
