# Generated by Django 5.2.17 on 2026-10-08 12:18

from django.db import migrations, models


def add_typography_tasks(apps, schema_editor):
    Task = apps.get_model('texts', 'AnthologyTask')
    Book = apps.get_model('texts', 'Anthology')
    db = schema_editor.connection.alias
    for pk in Book.objects.using(db).values_list('pk', flat=True).iterator():
        Task.objects.using(db).get_or_create(anthology_id=pk, task_type='cover_typography',
                                           defaults={'status': 'not_commissioned'})


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0030_remove_novel_final_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthologytask',
            name='task_type',
            field=models.CharField(choices=[('typesetting', 'Skład'), ('blurb', 'Blurb'), ('banners', 'Bannery'), ('cover_typography', 'Typografia okładki'), ('audio_description', 'Audiodeskrypcja')], max_length=20, verbose_name='rodzaj zadania'),
        ),
        migrations.RunPython(add_typography_tasks, migrations.RunPython.noop),
    ]
