# Generated by Django 5.2.18 on 2026-10-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0031_cover_typography_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthology',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'W przygotowaniu'), ('abandoned', 'Porzucona'), ('ready', 'Gotowa')], default='in_preparation', max_length=20, verbose_name='status'),
        ),
    ]
