# Generated by Django 5.2.18 on 2026-10-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_blacklistentry_options'),
        ('people', '0015_retire_generic_coordinator'),
        ('texts', '0032_abandoned_anthology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractTextLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=255)),
                ('source_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'powiązanie miniatury',
                'verbose_name_plural': 'powiązania miniatur',
            },
        ),
        migrations.CreateModel(
            name='ExtractVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], unique=True, verbose_name='tom')),
            ],
            options={
                'verbose_name': 'tom Ekstraktów',
                'verbose_name_plural': 'tomy Ekstraktów',
            },
        ),
        migrations.CreateModel(
            name='ExtractVolumeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='wykonana praca / etap')),
                ('source_name', models.CharField(blank=True, max_length=255, verbose_name='podpis w stopce')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'wykonana praca nad Ekstraktami',
                'verbose_name_plural': 'wykonane prace nad Ekstraktami',
                'ordering': ('anthology_id', 'position', 'pk'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='text',
            name='ordinary_text_requires_length',
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.CheckConstraint(condition=models.Q(('chapter_number__isnull', False), ('length__isnull', False), ('import_source', 'extracts-v1'), _connector='OR'), name='ordinary_text_requires_length'),
        ),
        migrations.AddField(
            model_name='extracttextlink',
            name='extract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_texts', to='texts.extract'),
        ),
        migrations.AddField(
            model_name='extracttextlink',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='extract_origin', to='texts.text'),
        ),
        migrations.AddField(
            model_name='extractvolume',
            name='anthology',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='extract_volume', to='texts.anthology'),
        ),
        migrations.AddField(
            model_name='extractvolumecredit',
            name='anthology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extract_credits', to='texts.anthology'),
        ),
        migrations.AddField(
            model_name='extractvolumecredit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extract_credits', to='people.person', verbose_name='osoba'),
        ),
        migrations.AddConstraint(
            model_name='extracttextlink',
            constraint=models.UniqueConstraint(fields=('extract', 'title_key'), name='unique_extract_accepted_title'),
        ),
        migrations.AddConstraint(
            model_name='extractvolumecredit',
            constraint=models.UniqueConstraint(fields=('anthology', 'person', 'role'), name='unique_extract_volume_credit'),
        ),
    ]
