# Generated by Django 5.2.18 on 2026-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0033_extract_volume_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthologytask',
            name='task_type',
            field=models.CharField(choices=[('typesetting', 'Skład'), ('blurb', 'Blurb'), ('banners', 'Banery'), ('cover_typography', 'Typografia okładki'), ('audio_description', 'Audiodeskrypcja')], max_length=20, verbose_name='rodzaj zadania'),
        ),
    ]
