# Generated by Django 5.2.18 on 2026-10-10 13:36

import django.db.models.deletion
from django.db import migrations, models
import unicodedata


def link_existing_cover_names(apps, schema_editor):
    Artist = apps.get_model('illustrations', 'Illustrator')
    Book = apps.get_model('texts', 'Anthology')
    alias = schema_editor.connection.alias
    def key(value):
        return ' '.join(unicodedata.normalize('NFC', value or '').split()).casefold()
    matches = {}
    for artist in Artist.objects.using(alias).all():
        for name in {key(f'{artist.first_name} {artist.last_name}'), key(artist.pseudonym)} - {''}:
            matches.setdefault(name, set()).add(artist.pk)
    for book in Book.objects.using(alias).exclude(cover_author='').iterator():
        ids = matches.get(key(book.cover_author), set())
        if len(ids) == 1:
            Book.objects.using(alias).filter(pk=book.pk).update(cover_illustrator_id=next(iter(ids)))


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0008_illustrator_pseudonym'),
        ('texts', '0034_audio_descriptions_and_banery'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthology',
            name='cover_illustrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anthology_covers', to='illustrations.illustrator', verbose_name='wykonawca okładki'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='cover_status',
            field=models.CharField(choices=[('not_started', 'Niezlecone'), ('in_progress', 'Zlecone'), ('ready', 'Gotowe')], default='not_started', max_length=20, verbose_name='stan okładki'),
        ),
        migrations.RunPython(link_existing_cover_names, migrations.RunPython.noop),
    ]
