# Generated by Django 5.2.18 on 2026-10-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_blacklistentry_options'),
        ('texts', '0035_anthology_cover_illustrator'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='text',
            name='ordinary_text_requires_length',
        ),
        migrations.AddField(
            model_name='anthology',
            name='cover_commissioned_at',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='data zlecenia okładki'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.CheckConstraint(condition=models.Q(('chapter_number__isnull', False), ('length__isnull', False), ('import_source__in', ('extracts-v1', 'extract-volume-v2')), _connector='OR'), name='ordinary_text_requires_length'),
        ),
    ]
