# Generated by Django 5.2.18 on 2026-10-10 16:27

from django.db import migrations, models


def flag_extract_anthologies(apps, schema_editor):
    # Previously recognised by the word "Ekstrakty" in the title or by an import marker.
    db = schema_editor.connection.alias
    Anthology = apps.get_model('texts', 'Anthology')
    Anthology.objects.using(db).filter(
        models.Q(title__icontains='ekstrakty') | models.Q(extract_volume__isnull=False)
    ).update(is_extracts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("texts", "0036_whole_extract_volumes_cover_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="anthology",
            name="is_extracts",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Antologia zbiorcza Ekstraktów: jeden wspólny tekst całego tomu z jednym workflow, miniatury tylko w rejestrze Ekstraktów.",
                verbose_name="Ekstrakty",
            ),
        ),
        migrations.RunPython(flag_extract_anthologies, migrations.RunPython.noop),
    ]
