# Generated by Django 5.2.18 on 2026-10-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texts", "0037_anthology_is_extracts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anthologytask",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_commissioned", "Niezlecone"),
                    ("commissioned", "Zlecone"),
                    ("ready", "Gotowe"),
                    ("not_applicable", "Nie dotyczy"),
                ],
                db_index=True,
                default="not_commissioned",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
