# Generated by Django 5.2.17 on 2026-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0002_prepare_illustration_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='coordinator_notes',
            field=models.TextField(blank=True, verbose_name='Uwagi koordynatora'),
        ),
        migrations.AddField(
            model_name='illustration',
            name='manual_illustrator_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail ilustratora (ręcznie)'),
        ),
        migrations.AddField(
            model_name='illustration',
            name='manual_illustrator_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ilustrator — imię i nazwisko (ręcznie)'),
        ),
    ]
