# Generated by Django 5.2.17 on 2026-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0003_illustration_coordinator_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='manual_illustrator_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ilustrator – imię i nazwisko (ręcznie)'),
        ),
    ]
