# Generated by Django 5.2.17 on 2026-10-06 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from django.core.management.color import no_style


def copy_contacts(apps, schema_editor):
    """Keep IDs so existing illustration assignments and directory links stay valid."""
    alias = schema_editor.connection.alias
    Person = apps.get_model('people', 'Person')
    Illustrator = apps.get_model('illustrations', 'Illustrator')
    Illustration = apps.get_model('illustrations', 'Illustration')
    role_ids = set(Person.objects.using(alias).filter(
        roles__name__iexact='Ilustrator').values_list('pk', flat=True))
    assigned_ids = set(Illustration.objects.using(alias).exclude(
        illustrator_id=None).values_list('illustrator_id', flat=True))
    # Preserve old contact data even if the person no longer has the role.
    candidates = Person.objects.using(alias).filter(
        models.Q(pk__in=role_ids | assigned_ids)
        | ~models.Q(illustrator_portfolio='')
        | ~models.Q(illustrator_preferences='')
        | models.Q(illustrator_covers=True)
    ).order_by('pk')
    for person in candidates.iterator():
        Illustrator.objects.using(alias).update_or_create(pk=person.pk, defaults={
            'first_name': person.first_name,
            'last_name': person.last_name,
            'email': person.email or None,
            'portfolio': person.illustrator_portfolio,
            'preferences': person.illustrator_preferences,
            'covers': person.illustrator_covers,
            'is_active': person.illustrator_active and person.pk in role_ids,
        })
    if assigned_ids - set(Illustrator.objects.using(alias).values_list('pk', flat=True)):
        raise RuntimeError('Nie udało się przenieść wszystkich przypisanych ilustratorów.')
    # Explicit IDs advance AUTO_INCREMENT on MySQL/SQLite; PostgreSQL needs a reset.
    for sql in schema_editor.connection.ops.sequence_reset_sql(no_style(), [Illustrator]):
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0004_alter_illustration_manual_illustrator_name'),
        ('people', '0012_person_illustrator_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='nazwisko')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='adres e-mail')),
                ('portfolio', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='portfolio')),
                ('preferences', models.TextField(blank=True, verbose_name='preferencje')),
                ('covers', models.BooleanField(default=False, verbose_name='okładki')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Wyłączenie ukrywa wpis w aktywnym spisie i przy nowych przypisaniach. Dotychczasowe prace pozostają.', verbose_name='aktywny ilustrator')),
            ],
            options={
                'verbose_name': 'wpis ilustratora',
                'verbose_name_plural': 'Ilustratorzy',
                'ordering': ('last_name', 'first_name', 'pk'),
            },
        ),
        # No reverse: new independent entries may have no corresponding Person.
        migrations.RunPython(copy_contacts),
        migrations.AlterField(
            model_name='illustration',
            name='illustrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='illustrations', to='illustrations.illustrator', verbose_name='ilustrator'),
        ),
    ]
