# Generated by Django 5.2.17 on 2026-10-08 13:44

import illustrations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0006_multiple_illustrators'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIllustrationSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('drive_url', models.URLField(blank=True, default='', help_text='Link publiczny, pokazywany przy każdym tekście w Zewnętrznych ilustracjach.', max_length=1000, validators=[illustrations.validators.validate_drive_url], verbose_name='wspólny link GDrive')),
            ],
            options={
                'verbose_name': 'ustawienia zewnętrznych ilustracji',
                'verbose_name_plural': 'Zewnętrzne ilustracje – ustawienia',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_public_illustration_settings')],
            },
        ),
    ]
