# Generated by Django 5.2.17 on 2026-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_add_typesetter_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='adres e-mail'),
        ),
    ]
