# Generated by Django 5.2.17 on 2026-09-14 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_phone_number'),
        ('people', '0007_coordinator_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='author_profile',
            field=models.OneToOneField(blank=True, help_text='Opcjonalne, jawne powiązanie. E-mail i pseudonim nie zastępują identyfikatora osoby.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to='authors.author', verbose_name='profil autora'),
        ),
    ]
