# Generated by Django 5.2.17 on 2026-10-03 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_unify_team_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='illustrator_covers',
            field=models.BooleanField(default=False, verbose_name='okładki'),
        ),
        migrations.AddField(
            model_name='person',
            name='illustrator_portfolio',
            field=models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='portfolio'),
        ),
        migrations.AddField(
            model_name='person',
            name='illustrator_preferences',
            field=models.TextField(blank=True, verbose_name='preferencje'),
        ),
    ]
