# Generated by Django 5.2.17 on 2026-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_person_illustrator_covers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='illustrator_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Wyłączenie ukrywa osobę w spisie ilustratorów i przy nowych przypisaniach. Dotychczasowe prace pozostają. Niezależne od członkostwa w zespole i konta.', verbose_name='Aktywny ilustrator'),
        ),
    ]
