# Generated by Django 5.2.18 on 2026-10-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_allow_missing_historical_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_external',
            field=models.BooleanField(db_index=True, default=False, help_text='Widoczny w zespole, bez logowania i udziału w raportach aktywności. Przypisania historyczne pozostają.', verbose_name='Zewnętrzny'),
        ),
        migrations.AddField(
            model_name='person',
            name='legacy_coordinator_access',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
