# Generated by Django 5.2.17 on 2026-09-21 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0011_alter_anthology_status'),
        ('workflow', '0002_mysql_verifier_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRepetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_stages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'powtórzenie etapów',
                'verbose_name_plural': 'powtórzenia etapów',
            },
        ),
        migrations.RemoveConstraint(
            model_name='workflowroleassignment',
            name='uniq_text_cycle_role',
        ),
        migrations.RemoveConstraint(
            model_name='workflowroleassignment',
            name='uniq_v1_v2_user_cycle',
        ),
        migrations.AddField(
            model_name='workflowroleassignment',
            name='execution_number',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='wykonanie przydziału'),
        ),
        migrations.AddField(
            model_name='workflowroleassignment',
            name='is_current',
            field=models.BooleanField(default=True, editable=False, verbose_name='aktualne przypisanie'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='assignment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stages', to='workflow.workflowroleassignment'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='execution_number',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='wykonanie etapu'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='is_current',
            field=models.BooleanField(default=True, editable=False, verbose_name='aktualne wykonanie'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='is_released',
            field=models.BooleanField(default=True, editable=False, verbose_name='dostępny w kolejce'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='queue_position',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='workflowrepetition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowrepetition',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='texts.text'),
        ),
        migrations.AddField(
            model_name='workflowroleassignment',
            name='repetition',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='workflow.workflowrepetition'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='repetition',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stages', to='workflow.workflowrepetition'),
        ),
        migrations.AddConstraint(
            model_name='workflowroleassignment',
            constraint=models.UniqueConstraint(fields=('text', 'workflow_cycle', 'role', 'execution_number'), name='uniq_text_role_execution'),
        ),
        migrations.AddConstraint(
            model_name='workflowroleassignment',
            constraint=models.UniqueConstraint(models.F('text'), models.F('workflow_cycle'), models.F('role'), models.Case(models.When(is_current=True, then=models.Value(1)), default=models.Value(None), output_field=models.IntegerField()), name='uniq_current_role_execution'),
        ),
        migrations.AddConstraint(
            model_name='workflowroleassignment',
            constraint=models.UniqueConstraint(models.F('text'), models.F('workflow_cycle'), models.F('assigned_to'), models.Case(models.When(is_current=True, role__in=('verifier_1', 'verifier_2'), then=models.Value(1)), default=models.Value(None), output_field=models.IntegerField()), name='uniq_v1_v2_user_cycle'),
        ),
    ]
