# Generated by Django 5.2.17 on 2026-09-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0011_alter_anthology_status'),
        ('workflow', '0004_bind_stage_history'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowstage',
            name='wf_stage_dates_valid',
        ),
        migrations.RemoveConstraint(
            model_name='workflowstage',
            name='wf_completed_has_dates',
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='imported_completed',
            field=models.BooleanField(default=False, editable=False, help_text='Wyłącznie import: zakończona praca może nie mieć znanych dat.', verbose_name='zakończony etap z importu'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), models.Q(('started_at__isnull', False), ('ended_at__gte', models.F('started_at'))), models.Q(('imported_completed', True), ('started_at__isnull', True)), _connector='OR'), name='wf_stage_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.CheckConstraint(condition=models.Q(('is_completed', False), ('imported_completed', True), models.Q(('started_at__isnull', False), ('ended_at__isnull', False)), _connector='OR'), name='wf_completed_has_dates'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.CheckConstraint(condition=models.Q(('imported_completed', False), ('is_completed', True), _connector='OR'), name='wf_import_is_completed'),
        ),
    ]
