# Generated by Django 5.2.17 on 2026-09-21 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0011_alter_anthology_status'),
        ('workflow', '0005_remove_workflowstage_wf_stage_dates_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrepetition',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowrepetition',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_workflow_repetitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowrepetition',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workflowrepetition',
            name='previous_assignment_ids',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name='workflowrepetition',
            name='previous_stage_ids',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.CreateModel(
            name='WorkflowHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_started_at', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs_to', to='workflow.workflowroleassignment')),
                ('previous_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs_from', to='workflow.workflowroleassignment')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs', to='workflow.workflowstage')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_handoffs', to='texts.text')),
            ],
            options={
                'verbose_name': 'przekazanie pracy',
                'verbose_name_plural': 'przekazania pracy',
            },
        ),
    ]
