# Generated by Django 5.2.17 on 2026-09-21 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0013_alter_review_old_reviews'),
        ('workflow', '0007_repetition_restore_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowroleassignment',
            name='role',
            field=models.CharField(choices=[('editor', 'Redaktor'), ('editing_coordinator', 'K. redakcji'), ('proofreader_1', 'Korektor 1'), ('proofreader_2', 'Korektor 2'), ('proofreader_3', 'Korektor 3'), ('proofreader_4', 'Korektor 4'), ('verifier_1', 'Weryfikator 1'), ('verifier_2', 'Weryfikator 2'), ('verifier_3', 'Weryfikator 3'), ('verification_coordinator', 'K. weryfikacji'), ('styling', 'Stylowanie'), ('editing_reviewer', 'Kontrola redakcji'), ('verifier_4', 'Weryfikator 4')], max_length=30, verbose_name='rola'),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='stage_type',
            field=models.CharField(choices=[('ready_for_editing', 'Do redakcji'), ('editing', 'Redakcja'), ('first_verification', 'Pierwsza weryfikacja'), ('author_editing', 'Plik u autora (redakcja)'), ('second_verification', 'Druga weryfikacja'), ('editing_control', 'Kontrola K. redakcji'), ('first_proofreading', 'Pierwsza korekta'), ('second_proofreading', 'Druga korekta'), ('third_verification', 'Trzecia weryfikacja'), ('coordinator_control', 'Kontr. wer. (koordynator)'), ('editor_control', 'Kontr. wer. (redaktor)'), ('third_proofreading', 'Trzecia korekta'), ('fourth_proofreading', 'Czwarta korekta'), ('styling', 'Stylowanie'), ('ready', 'Gotowe'), ('withdrawn', 'WYCOFANY'), ('editing_review', 'Kontrola redakcji'), ('fourth_verification', 'Czwarta weryfikacja')], max_length=30, verbose_name='etap'),
        ),
        migrations.AddConstraint(
            model_name='workflowroleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ('editing_reviewer', 'verifier_4')), _negated=True), models.Q(('is_current', False), ('repetition__isnull', True)), _connector='OR'), name='wf_import_role_not_current'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage_type__in', ('editing_review', 'fourth_verification')), _negated=True), models.Q(('imported_completed', True), ('is_completed', True), ('is_current', False), ('is_released', False), ('repetition__isnull', True)), _connector='OR'), name='wf_import_only_closed'),
        ),
    ]
