# Generated by Django 5.2.17 on 2026-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0013_alter_review_old_reviews'),
        ('workflow', '0008_import_only_work'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowstage',
            name='wf_completed_has_dates',
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='is_skipped',
            field=models.BooleanField(default=False, editable=False, verbose_name='pominięty etap'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.CheckConstraint(condition=models.Q(('is_skipped', False), models.Q(('assignment__isnull', True), ('ended_at__isnull', True), ('imported_completed', False), ('is_completed', True), ('stage_type', 'fourth_proofreading'), ('started_at__isnull', True)), _connector='OR'), name='wf_skipped_empty'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.CheckConstraint(condition=models.Q(('is_completed', False), ('imported_completed', True), ('is_skipped', True), models.Q(('started_at__isnull', False), ('ended_at__isnull', False)), _connector='OR'), name='wf_completed_has_dates'),
        ),
    ]
