# Generated by Django 5.2.17 on 2026-10-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_remove_workflowstage_wf_completed_has_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='queued_at',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='data wejścia do kolejki'),
        ),
    ]
