# Generated by Django 5.2.17 on 2026-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_merge_duplicate_role_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='send_to_proofreading',
            field=models.BooleanField(blank=True, editable=False, help_text='Decyzja koordynatora redakcji; brak wartości oznacza dawną historię.', null=True, verbose_name='przekazać do pierwszej korekty'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='waiting_reset_at',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='data zmiany wykonawcy'),
        ),
    ]
